<a href="https://colab.research.google.com/github/fMurugi/complete-neural-network-course/blob/main/learn_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
b = torch.tensor([2,3,4])
print(b)

tensor([2, 3, 4])


In [3]:
b.shape

torch.Size([3])

In [4]:
b.view(-1,1)

tensor([[2],
        [3],
        [4]])

In [5]:
c= torch.tensor([[1,2,3],[4,5,6]])
print(c)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [6]:
c.shape
c.view(6) # 1 row by 6 cols
c.view(-1,2) # i want to change tje shape to n rows by 2 columns

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [7]:
# create a 3d tensor
d = torch.randn(2,3,4)
print(d)
print(d.view(2,12))

tensor([[[-0.9176,  0.2258,  0.0474,  1.3025],
         [ 0.7625,  0.4741, -0.3093, -0.6855],
         [-1.8784,  1.4958, -1.0740, -1.3366]],

        [[ 0.0808,  2.2064,  0.7452, -1.1585],
         [-0.8553, -0.4479,  0.4707, -0.1505],
         [ 0.4276, -0.0807,  1.3967, -0.9548]]])
tensor([[-0.9176,  0.2258,  0.0474,  1.3025,  0.7625,  0.4741, -0.3093, -0.6855,
         -1.8784,  1.4958, -1.0740, -1.3366],
        [ 0.0808,  2.2064,  0.7452, -1.1585, -0.8553, -0.4479,  0.4707, -0.1505,
          0.4276, -0.0807,  1.3967, -0.9548]])


In [8]:
#create a matrix of random numbers btn 0 and 1
r1 =torch.rand(4,4)
print(r1)

tensor([[0.2680, 0.0607, 0.8573, 0.4914],
        [0.9563, 0.0734, 0.4707, 0.2145],
        [0.5031, 0.3445, 0.2905, 0.7859],
        [0.4677, 0.9824, 0.5405, 0.2399]])


In [9]:
#create a matrix of random numbers from a normal distribution with mean 0 and variance 1
r2 = torch.randn(4,4)
print(r2)

tensor([[ 2.3231, -0.9414, -1.4617,  0.2335],
        [-0.2451, -0.5499, -0.3668,  0.0987],
        [ 0.4367, -1.9768, -1.3397, -0.7864],
        [-1.4837,  1.2151,  0.4722,  1.7268]])


In [10]:
r2.add_(r1) #modifying r2 in place
print(r2)

tensor([[ 2.5911e+00, -8.8072e-01, -6.0437e-01,  7.2489e-01],
        [ 7.1127e-01, -4.7645e-01,  1.0395e-01,  3.1320e-01],
        [ 9.3981e-01, -1.6324e+00, -1.0492e+00, -4.5747e-04],
        [-1.0160e+00,  2.1975e+00,  1.0127e+00,  1.9667e+00]])


In [11]:
print(r2[:,1])

tensor([-0.8807, -0.4765, -1.6324,  2.1975])


In [12]:
import numpy as np

In [13]:
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [14]:
b = torch.from_numpy(a)
print(b)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [15]:
np.add(a,1,out=a)
print(a)

[2. 2. 2. 2. 2.]


Tensor concatenation

AutoGrad

if you want to keep track of how tensor object was created you need requires_grad set to true.
Then you can create gradient in respect to the objects/variables

In [19]:
x = torch.tensor([1,2,3],dtype=torch.float32,requires_grad=True)
y = torch.tensor([3.,4.,5.],requires_grad=True)
z=x+y
print(z)
print(z.grad_fn)

tensor([4., 6., 8.], grad_fn=<AddBackward0>)


In [21]:
s= z.sum()
print(s)
print(s.grad_fn)

tensor(18., grad_fn=<SumBackward0>)


In [22]:
s.backward()
print(x.grad)

tensor([1., 1., 1.])


In [23]:
# you can detach a tensor from its history of computation

In [ ]:
#you can also stop autograd from tracking history on tensors. it is useful on transfer learning

Loss functions in pytorch

In [24]:
import torch
import torch.nn as nn

In [25]:
prediction = torch.randn(4,5)

In [26]:
label = torch.randn(4,5)

In [31]:
mse = nn.MSELoss(reduction='mean')

In [32]:
loss = mse(prediction,label)

In [33]:
loss

tensor(1.8037)

In [36]:
((prediction-label)**2).mean() #implementation of MSE

tensor(1.8037)

Binary Cross Entropy with sigmoid fn

In [38]:
prediction

tensor([[-2.0730e-01, -2.5479e-01,  3.6638e-01, -1.8112e+00,  1.1963e-02],
        [ 7.0848e-01, -6.7240e-01, -5.0439e-01,  1.5985e+00, -1.8195e-03],
        [ 1.7767e+00,  5.1060e-01,  1.0014e+00,  4.2208e-01, -1.2883e-01],
        [-1.9693e+00,  8.8629e-01,  1.4834e+00, -1.4580e+00,  8.8723e-01]])

In [40]:
label = torch.zeros(4,5).random_(0,2)
label

tensor([[0., 0., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 0., 0., 0., 1.],
        [0., 1., 0., 1., 0.]])

In [41]:
sigmoid = nn.Sigmoid()


In [42]:
bce=nn.BCELoss(reduction='mean')

In [46]:
bce(sigmoid(prediction),label)

tensor(0.7542)

binary cross entropy with logits


In [48]:
bces = bce = nn.BCEWithLogitsLoss(reduction='mean')

In [49]:
bces(prediction,label)

tensor(0.7542)

In [51]:
# implement bce manually
import numpy as np
x = prediction.numpy()
y = label.numpy()


In [54]:
def sigmoid(x):
  return 1/ (1+np.exp(-x))

In [55]:
sigmoid(x)

array([[0.44835877, 0.43664503, 0.5905845 , 0.1404888 , 0.50299066],
       [0.6700662 , 0.33795854, 0.3765107 , 0.8318051 , 0.4995451 ],
       [0.85529363, 0.6249465 , 0.7313407 , 0.6039806 , 0.4678367 ],
       [0.12246132, 0.7081232 , 0.815088  , 0.1887781 , 0.7083172 ]],
      dtype=float32)

In [56]:
loss_values =[]
x= sigmoid(x) # ensure values are between 0 and 1
for i in range(len(y)):
  batch_loss=[]
  for j in range(len(y[0])):
    if y[i][j]==1:
      batch_loss.append(-np.log(x[i][j]))
    else:
      batch_loss.append(-np.log(1-x[i][j]))
  loss_values.append(batch_loss)
print(np.mean(loss_values))

0.7542226


**Weight initialization**

In [57]:
import torch
import torch.nn as nn


In [59]:
layer = nn.Linear(5,5)


In [61]:
layer.weight.data

tensor([[ 0.4273, -0.3493, -0.1255, -0.4063, -0.0689],
        [-0.2725, -0.2112,  0.2881,  0.0077, -0.0219],
        [-0.2615,  0.2213, -0.2350, -0.1664,  0.1978],
        [ 0.1835, -0.1304,  0.1026,  0.0307,  0.1937],
        [-0.1510,  0.2295,  0.2222,  0.3997, -0.4417]])

In [62]:
nn.init.uniform_(layer.weight.data,a=0,b=3) # equal chance  probability =1/(max-min)

tensor([[1.6088, 1.3230, 2.1245, 1.1926, 0.5779],
        [1.1128, 0.8896, 1.7273, 1.3628, 0.0933],
        [0.3820, 2.4273, 1.8663, 0.1946, 2.2222],
        [1.0877, 2.2663, 0.8122, 2.5647, 0.1156],
        [0.4619, 0.8460, 2.5933, 1.0995, 2.3968]])

In [64]:
nn.init.normal_(layer.weight,mean=0,std=0.2) # measure height of people or IQ scoresm bell like shape

Parameter containing:
tensor([[ 0.0760, -0.0231, -0.1340,  0.2224, -0.1960],
        [-0.1208, -0.0936, -0.0744, -0.3259,  0.0464],
        [-0.1588,  0.0450,  0.3368,  0.1408, -0.0979],
        [-0.3721,  0.1476, -0.2387, -0.1656, -0.0247],
        [ 0.0567,  0.2140, -0.4360, -0.1647, -0.0943]], requires_grad=True)

In [65]:
#xavier initialization
nn.init.xavier_uniform_(layer.weight)

Parameter containing:
tensor([[ 0.3899, -0.4328, -0.7066, -0.4597,  0.6958],
        [-0.5030, -0.3827, -0.3455, -0.1636,  0.6213],
        [ 0.4002,  0.7420,  0.2983, -0.6383,  0.7178],
        [ 0.7152, -0.7688, -0.7703, -0.2600, -0.6009],
        [-0.4577, -0.1178, -0.7429,  0.1993,  0.5286]], requires_grad=True)

DATA AUGMENTATION : get different versions of what you have ,apply some transformations of the images of you.And achieve betterperfromance without extra labels

MixUp